### ISSUE TITLE
[0.0.13]  Playwright doesnt start

### ISSUE THREAD

**Issue by Moep90** [trypromptly/LLMStack#47]
# Describe the bug
Unable to add localAI to docker-compose and testing it since URL requires TLD

# To Reproduce

# Start the stack
1. unzip v0.0.13
2. `docker-compse pull`
3. `docker-compose up -d`
4. `docker-compose logs -f`

# Version
v0.0.13

# Environment
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
Docker version 24.0.5, build ced0996
Docker Compose version v2.20.3

# Screenshots

# Additional context
```
llmstack-0013-playwright-1  | node:internal/process/promises:288
llmstack-0013-playwright-1  |             triggerUncaughtException(err, true /* fromPromise */);
llmstack-0013-playwright-1  |             ^
llmstack-0013-playwright-1  | Error: Executable doesn't exist at /ms-playwright/chromium-1080/chrome-linux/chrome
llmstack-0013-playwright-1  | ╔══════════════════════════════════════════════════════════════════════╗
llmstack-0013-playwright-1  | ║ Looks like Playwright Test or Playwright was just updated to 1.38.1. ║
llmstack-0013-playwright-1  | ║ Please update docker image as well.                                  ║
llmstack-0013-playwright-1  | ║ -  current: mcr.microsoft.com/playwright:v1.37.0-jammy               ║
llmstack-0013-playwright-1  | ║ - required: mcr.microsoft.com/playwright:v1.38.1-jammy               ║
llmstack-0013-playwright-1  | ║                                                                      ║
llmstack-0013-playwright-1  | ║ <3 Playwright Team                                                   ║
llmstack-0013-playwright-1  | ╚══════════════════════════════════════════════════════════════════════╝ Failed to launch browser.
llmstack-0013-playwright-1  |     at executablePathOrDie (/home/pwuser/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core/lib/server/registry/index.js:357:15)
llmstack-0013-playwright-1  |     at Object.executablePathOrDie (/home/pwuser/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core/lib/server/registry/index.js:370:43)
llmstack-0013-playwright-1  |     at Chromium._launchProcess (/home/pwuser/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core/lib/server/browserType.js:166:39)
llmstack-0013-playwright-1  |     at async Chromium._innerLaunch (/home/pwuser/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core/lib/server/browserType.js:103:9)
llmstack-0013-playwright-1  |     at async Chromium._innerLaunchWithRetries (/home/pwuser/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core/lib/server/browserType.js:84:14)
llmstack-0013-playwright-1  |     at async ProgressController.run (/home/pwuser/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core/lib/server/progress.js:92:22)
llmstack-0013-playwright-1  |     at async Chromium.launch (/home/pwuser/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core/lib/server/browserType.js:61:21)
llmstack-0013-playwright-1  |     at async BrowserServerLauncherImpl.launchServer (/home/pwuser/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core/lib/browserServerImpl.js:48:21)
llmstack-0013-playwright-1  |     at async launchBrowserServer (/home/pwuser/.npm/_npx/e41f203b7505f1fb/node_modules/playwright-core/lib/cli/driver.js:86:18)
llmstack-0013-playwright-1  | Node.js v18.17.1
llmstack-0013-playwright-1 exited with code 1

```

**Comment by ajhai** [comment]
@Moep90 this should be fixed in 0.0.15. Thanks for reporting this.
